# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsddaSSHLOEIHalzUyQ7XEvC_5xLKC0N
"""

import numpy as np
import json
from sklearn.cluster import KMeans
from google.colab import files

def generar_puntos(n=300):
    puntos = []
    for _ in range(n):
        x = np.random.uniform(-50, 50)
        y = np.random.uniform(-50, 50)
        # Altura tipo montañas
        z = np.sin(x * 0.05) * np.cos(y * 0.05) * 10
        puntos.append([x, y, z])
    return np.array(puntos)

puntos = generar_puntos()

kmeans = KMeans(n_clusters=3).fit(puntos)
labels = kmeans.labels_

data = [
    {"x": float(x), "y": float(y), "z": float(z), "label": int(label)}
    for (x, y, z), label in zip(puntos, labels)
]
with open("ecosistema.json", "w") as f:
    json.dump(data, f)

files.download("ecosistema.json")